# Generated by Django 3.0.8 on 2020-08-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default=models.CharField(blank=True, max_length=255, null=True, unique=True), max_length=255),
        ),
    ]
