# Generated by Django 3.0.8 on 2020-08-04 20:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200804_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
