# Generated by Django 3.0.8 on 2020-08-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20200810_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_excerpt',
            field=models.TextField(blank=True, max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='specialty',
            field=models.CharField(blank=True, choices=[('01', 'Clarividencia'), ('02', 'Exploración de Sueños'), ('03', 'Tarot'), ('04', 'Numerancia'), ('05', 'Péndulo'), ('06', 'Carta Kármica')], max_length=2, null=True),
        ),
    ]
