# Generated by Django 3.0.8 on 2020-08-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialties', '0003_remove_specialty_user'),
        ('profiles', '0009_auto_20200816_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='specialty',
        ),
        migrations.AddField(
            model_name='profile',
            name='specialty',
            field=models.ManyToManyField(blank=True, null=True, to='specialties.Specialty'),
        ),
    ]
