# Generated by Django 3.0.8 on 2020-08-18 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_profile_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='item',
        ),
    ]
