# Generated by Django 3.0.8 on 2020-08-18 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_item_owner'),
        ('profiles', '0013_remove_profile_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cart.Item'),
            preserve_default=False,
        ),
    ]
