# Generated by Django 3.0.8 on 2020-08-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('co', 'consulta'), ('cl', 'clase'), ('le', 'lectura')], default='co', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('pr', 'primary'), ('se', 'secondary'), ('da', 'danger')], default='pr', max_length=2),
            preserve_default=False,
        ),
    ]
