# Generated by Django 3.0.8 on 2020-08-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20200817_1558'),
        ('cart', '0002_auto_20200818_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.ManyToManyField(blank=True, to='profiles.Profile'),
        ),
    ]
