# Generated by Django 3.0.8 on 2020-08-18 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_item_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='owner',
        ),
    ]
