# Generated by Django 3.0.8 on 2020-08-18 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_remove_profile_item'),
        ('cart', '0004_remove_item_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
            preserve_default=False,
        ),
    ]
