# Generated by Django 3.0.8 on 2020-08-18 20:09

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_item_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'item', 'verbose_name_plural': 'items'},
        ),
        migrations.AddField(
            model_name='item',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='slug', editable=False, populate_from='title'),
            preserve_default=False,
        ),
    ]
