# Generated by Django 3.0.8 on 2020-08-19 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20200818_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='owner',
            new_name='profile',
        ),
    ]
