# Generated by Django 3.0.8 on 2020-08-15 23:41

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty_name', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='specialty_name')),
                ('specialty_excerpt', models.CharField(blank=True, max_length=280, null=True)),
                ('specialty_text', models.TextField(blank=True, max_length=1255, null=True)),
                ('picture', models.ImageField(blank=True, max_length=255, null=True, upload_to='specialties_pics')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
    ]
