# Generated by Django 3.0.8 on 2020-08-15 23:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('specialties', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Specialties',
            new_name='Specialty',
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={'verbose_name': 'specialty', 'verbose_name_plural': 'specialties'},
        ),
    ]
