# Generated by Django 3.0.8 on 2020-08-16 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialties', '0002_auto_20200815_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialty',
            name='user',
        ),
    ]
